services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins-with-tools:latest
    container_name: jenkins-master
    user: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
      - "C:\\Users\\Rishi Raj\\.kube\\config:/home/jenkins/.kube/config:ro"
    restart: unless-stopped
